AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Practicing Cognito user pool

Parameters:
  AppName:
    Type: String
    Description: Name of the application
  ClientDomains:
    Type: CommaDelimitedList
    Description: List of domains
  UserEmail:
    Type: String
    Description: Admin email address

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AppName}-UserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub ${AppName}-UserPoolClient
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs: !Ref ClientDomains
      LogoutURLs: !Ref ClientDomains
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
        # - client_credentials
      AllowedOAuthScopes:
        - email
        - openid
        - profile

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: !Sub ${AppName}-${AWS::AccountId}
      UserPoolId: !Ref UserPool

  UserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      GroupName: Users
      Description: User Group
      Precedence: 0
      UserPoolId: !Ref UserPool

  # GeneralUser:
  #   Type: AWS::Cognito::UserPoolUser
  #   Properties:
  #     Username: !Ref UserEmail
  #     DesiredDeliveryMediums: 
  #       - EMAIL
  #     ForceAliasCreation: true
  #     UserAttributes: 
  #       - Name: email
  #         Value: !Ref UserEmail
  #     UserPoolId: !Ref UserPool
        
  # AddUserToUserGroup:
  #   Type: AWS::Cognito::UserPoolUserToGroupAttachment
  #   Properties: 
  #     GroupName: !Ref UserGroup
  #     Username: !Ref GeneralUser
  #     UserPoolId: !Ref UserPool

  TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 5
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: src/
      Events:
        CognitoTrigger:
          Type: Cognito
          Properties:
            # Trigger: PreSignUp
            Trigger: PreAuthentication
            UserPool: !Ref UserPool


Outputs:
  UserPoolId:
    Description: "User pool ID"
    Value: !Ref UserPool
    Export:
      Name: !Sub ${AppName}:UserPoolId

  UserPoolClientId:
    Description: "Application client ID"
    Value: !Ref UserPoolClient

  AuthUrl:
    Description: "URL used for authentication"
    Value: !Sub https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com
